FROM agustinallamano/zkp:latest
WORKDIR /src
COPY ./src/api ./api
COPY ./src/__init__.py .
COPY ./src/app.py .
COPY ./src/requirements.txt .
COPY ./src/zkp/ ./zkp/

RUN pip3 install -r ./requirements.txt

ENV LC_ALL=C.UTF-8 
ENV LANG=C.UTF-8

EXPOSE 80
EXPOSE 8080
RUN export FLASK_APP=src/main.py
CMD ["flask","run","--port","80"]
