FROM agustinallamano/zkp:latest
WORKDIR /src
COPY ./src/requirements.txt .
COPY ./src/api ./api

RUN pip3 install -r ./requirements.txt

ENV LC_ALL=C.UTF-8 
ENV LANG=C.UTF-8

EXPOSE 80
RUN pwd && ls
CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=80"]
