FROM agustinallamano/zkp:latest
WORKDIR /src
COPY ./src/api ./api
COPY ./src/__init__.py .
COPY ./src/main.py .
COPY ./src/requirements.txt .
COPY ./src/zkp/ ./zkp/

RUN pip3 install -r ./requirements.txt

ENV LC_ALL=C.UTF-8 
ENV LANG=C.UTF-8

EXPOSE 80
EXPOSE 8080

CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=80"]
# uvicorn "main:app" --host=0.0.0.0  --port=80
